package entidades;
// Generated 12-09-2021 23:13:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Due�o generated by hbm2java
 */
public class Dueño  implements java.io.Serializable {


     private int rut;
     private String nombre;
     private String apellido;
     private String direccion;
     private String correo;
     private String telefono;
     private String nombreMascota;
     private Set mascotas = new HashSet(0);

    public Dueño() {
    }

	
    public Dueño(int rut) {
        this.rut = rut;
    }
    public Dueño(int rut, String nombre, String apellido, String direccion, String correo, String telefono, String nombreMascota, Set mascotas) {
       this.rut = rut;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.correo = correo;
       this.telefono = telefono;
       this.nombreMascota = nombreMascota;
       this.mascotas = mascotas;
    }
   
    public int getRut() {
        return this.rut;
    }
    
    public void setRut(int rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getNombreMascota() {
        return this.nombreMascota;
    }
    
    public void setNombreMascota(String nombreMascota) {
        this.nombreMascota = nombreMascota;
    }
    public Set getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set mascotas) {
        this.mascotas = mascotas;
    }




}


