package entidades;
// Generated 12-09-2021 23:13:15 by Hibernate Tools 4.3.1



/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private Integer idMascota;
     private Dueño dueño;
     private String tipoMascota;
     private String edad;
     private String nombreMascota;

    public Mascota() {
    }

    public Mascota(Dueño dueño, String tipoMascota, String edad, String nombreMascota) {
       this.dueño = dueño;
       this.tipoMascota = tipoMascota;
       this.edad = edad;
       this.nombreMascota = nombreMascota;
    }
   
    public Integer getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(Integer idMascota) {
        this.idMascota = idMascota;
    }
    public Dueño getDueño() {
        return this.dueño;
    }
    
    public void setDueño(Dueño dueño) {
        this.dueño = dueño;
    }
    public String getTipoMascota() {
        return this.tipoMascota;
    }
    
    public void setTipoMascota(String tipoMascota) {
        this.tipoMascota = tipoMascota;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getNombreMascota() {
        return this.nombreMascota;
    }
    
    public void setNombreMascota(String nombreMascota) {
        this.nombreMascota = nombreMascota;
    }




}


